analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.4375
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#1E394B'
    - '#927F79'
    - '#BDDFE0'
    - '#ABACA3'
  rhythmicContrast: 0.5
typography_spectrum: 0.1684588
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.9408602
favicon: null
name: The kinln
